"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1l2$q+wj@^$@ije4ag280j3f@-zu!mfwdm^5xfrzv37z#zzc8f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]  # For testing purposes only, change this in production

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Local apps
    "accounts.apps.AccountsConfig",
    "home.apps.HomeConfig",
    "blog.apps.BlogConfig",
    # Third party apps
    "crispy_forms",
    "crispy_bootstrap5",
    "tinymce",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Account settings
AUTH_USER_MODEL = "accounts.CustomUser"

LOGIN_REDIRECT_URL = "blog"
LOGOUT_REDIRECT_URL = "blog"

# Email backend
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@neutronweb.com"
EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_HOST_USER = "apikey"
EMAIL_HOST_PASSWORD = (
    "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"
)
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Third party settings
# Crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# TinyMCE
TINYMCE_JS_URL = "tinymce/tinymce.min.js"
TINYMCE_JS_ROOT = "static/tinymce"
TINYMCE_DEFAULT_CONFIG = {
    "height": 500,
    # # "width": 750,
    "cleanup_on_startup": True,
    "custom_undo_redo_levels": 20,
    "selector": "textarea",
    "theme": "silver",
    "plugins": """
            emoticons hr link image media preview codesample contextmenu
            code lists charmap fullscreen insertdatetime wordcount
            autolink anchor spellchecker
            """,
    "contextmenu": "formats | link | image",
    "menubar": True,
    "statusbar": True,
    "mobile": {
        "menubar": True,
        "height": 300,
    },
    "toolbar": "undo redo formatgroup paragraphgroup insertgroup code codesample",
    "toolbar_groups": {
        "formatgroup": {
            "icon": "format",
            "tooltip": "Formatting",
            "items": "bold italic underline strikethrough | forecolor backcolor | superscript subscript | removeformat",
        },
        "paragraphgroup": {
            "icon": "paragraph",
            "tooltip": "Paragraph format",
            "items": "h1 h2 h3 | bullist numlist | alignleft aligncenter alignright | indent outdent",
        },
        "insertgroup": {
            "icon": "plus",
            "tooltip": "Insert",
            "items": "link image emoticons charmap hr",
        },
    },
    # "toolbar1": """
    #         undo redo | styleselect fontselect fontsizeselect|
    #         fullscreen preview bold italic | forecolor | code codesample |
    #         bullist numlist table | link image media |
    #         """,
    # "toolbar2": """
    #         """,
}
TINYMCE_SPELLCHECKER = True
# TINYMCE_COMPRESSOR = True
